
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson 
      Build flags: 
      Id flags:  
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson 
      Build flags: 
      Id flags: -c 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson 
      Build flags: 
      Id flags: -Aa 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson 
      Build flags: 
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson 
      Build flags: 
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson 
      Build flags: 
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson 
      Build flags: 
      Id flags:  
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson 
      Build flags: 
      Id flags: -c 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson 
      Build flags: 
      Id flags: -Aa 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson 
      Build flags: 
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson 
      Build flags: 
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson 
      Build flags: 
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
  -
    kind: "message-v1"
    backtrace:
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:1284 (message)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeDetermineCompilerABI.cmake:83 (try_compile)"
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-xj61sf"
      binary: "C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-xj61sf"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-xj61sf'
        
        Run Build Command(s): "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/bin/cmake.exe" -E env VERBOSE=1 "D:/INSTALLED/Clion/CLion 2025.2.5/bin/mingw/bin/mingw32-make.exe" -f Makefile cmTC_0d343/fast
        D:/INSTALLED/Clion/CLion 2025.2.5/bin/mingw/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_0d343.dir\\build.make CMakeFiles/cmTC_0d343.dir/build
        mingw32-make[1]: Entering directory 'C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-xj61sf'
        Building C object CMakeFiles/cmTC_0d343.dir/CMakeCCompilerABI.c.obj
        C:\\Users\\NICKSON\\CLionProjects\\CFONB_Analyser_Tchinda_Fotsa_Nickson    -o CMakeFiles\\cmTC_0d343.dir\\CMakeCCompilerABI.c.obj -c "D:\\INSTALLED\\Clion\\CLion 2025.2.5\\bin\\cmake\\win\\x64\\share\\cmake-4.0\\Modules\\CMakeCCompilerABI.c"
        process_begin: CreateProcess(NULL, C:\\Users\\NICKSON\\CLionProjects\\CFONB_Analyser_Tchinda_Fotsa_Nickson -o CMakeFiles\\cmTC_0d343.dir\\CMakeCCompilerABI.c.obj -c "D:\\INSTALLED\\Clion\\CLion 2025.2.5\\bin\\cmake\\win\\x64\\share\\cmake-4.0\\Modules\\CMakeCCompilerABI.c", ...) failed.
        make (e=5): Access is denied.\x0d
        mingw32-make[1]: *** [CMakeFiles\\cmTC_0d343.dir\\build.make:80: CMakeFiles/cmTC_0d343.dir/CMakeCCompilerABI.c.obj] Error 5
        mingw32-make[1]: Leaving directory 'C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-xj61sf'
        mingw32-make: *** [Makefile:133: cmTC_0d343/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/share/cmake-4.0/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C compiler: C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson"
    directories:
      source: "C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-zf2prr"
      binary: "C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-zf2prr"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-zf2prr'
        
        Run Build Command(s): "D:/INSTALLED/Clion/CLion 2025.2.5/bin/cmake/win/x64/bin/cmake.exe" -E env VERBOSE=1 "D:/INSTALLED/Clion/CLion 2025.2.5/bin/mingw/bin/mingw32-make.exe" -f Makefile cmTC_3e7dc/fast
        D:/INSTALLED/Clion/CLion 2025.2.5/bin/mingw/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_3e7dc.dir\\build.make CMakeFiles/cmTC_3e7dc.dir/build
        mingw32-make[1]: Entering directory 'C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-zf2prr'
        Building C object CMakeFiles/cmTC_3e7dc.dir/testCCompiler.c.obj
        C:\\Users\\NICKSON\\CLionProjects\\CFONB_Analyser_Tchinda_Fotsa_Nickson    -o CMakeFiles\\cmTC_3e7dc.dir\\testCCompiler.c.obj -c C:\\Users\\NICKSON\\CLionProjects\\CFONB_Analyser_Tchinda_Fotsa_Nickson\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-zf2prr\\testCCompiler.c
        process_begin: CreateProcess(NULL, C:\\Users\\NICKSON\\CLionProjects\\CFONB_Analyser_Tchinda_Fotsa_Nickson -o CMakeFiles\\cmTC_3e7dc.dir\\testCCompiler.c.obj -c C:\\Users\\NICKSON\\CLionProjects\\CFONB_Analyser_Tchinda_Fotsa_Nickson\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-zf2prr\\testCCompiler.c, ...) failed.
        make (e=5): Access is denied.\x0d
        mingw32-make[1]: *** [CMakeFiles\\cmTC_3e7dc.dir\\build.make:80: CMakeFiles/cmTC_3e7dc.dir/testCCompiler.c.obj] Error 5
        mingw32-make[1]: Leaving directory 'C:/Users/NICKSON/CLionProjects/CFONB_Analyser_Tchinda_Fotsa_Nickson/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-zf2prr'
        mingw32-make: *** [Makefile:133: cmTC_3e7dc/fast] Error 2
        
      exitCode: 2
...
